name: Weekly run of wolf-bites-tweets

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 1'

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Run WBT
        uses: ohmykreee/wolf-bites-tweets@v2
        with:
          screen-name: kreeejiang
          bearer-token: ${{ secrets.BEARER_TOKEN }}
          get-type: likes
          count: 50,50
          if-only-media: true

      - name: Force-push to branch "data"
        if: success()
        uses: dfm/force-push-branch-action@v1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          path: output
          target-branch: data