name: Test the function of Wolf-Bites-Tweets

on:
  push:
    branches:
      - dev

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Run WBT
        uses: ohmykreee/wolf-bites-tweets@v2
        with:
          screen-name: kreeejiang
          bearer-token: ${{ secrets.BEARER_TOKEN }}
          get-type: both
          count: 10,15
          if-only-media: false

      - name: Force-push to branch "data-dev"
        if: success()
        uses: dfm/force-push-branch-action@v1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          path: output
          target-branch: data-dev