name: Test the function of Wolf-Bites-Tweets

on:
  push:
    branches:
      - dev

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Run WBT
        uses: ohmykreee/wolf-bites-tweets@1.0.7
        with:
          screen_name: kreeejiang
          bearer_token: ${{ secrets.BEARER_TOKEN }}
          get_type: both
          count: 10,15
          if_only_media: false

      - name: Force-push to branch "data"
        if: success()
        uses: dfm/force-push-branch-action@v1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          path: output
          target-branch: data-dev